export const errorCodes = {
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DNS_LOOKUP_FAILED: "DNS_LOOKUP_FAILED",
  SMTP_CONNECTION_FAILED: "SMTP_CONNECTION_FAILED",
  TIMEOUT: "TIMEOUT",
} as const;
