export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	NOT_MEMBER_OF_ORGANIZATION: "NOT_MEMBER_OF_ORGANIZATION",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
	INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
	CREDIT_RECORD_NOT_FOUND: "CREDIT_RECORD_NOT_FOUND",
	DATABASE_ERROR: "DATABASE_ERROR",
	INVALID_AMOUNT: "INVALID_AMOUNT",
} as const;
