export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	NOT_MEMBER_OF_ORGANIZATION: "NOT_MEMBER_OF_ORGANIZATION",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	API_KEY_ALREADY_EXISTS: "API_KEY_ALREADY_EXISTS",
	API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
	API_KEY_INVALID: "API_KEY_INVALID",
	API_KEY_EXPIRED: "API_KEY_EXPIRED",
	API_KEY_DISABLED: "API_KEY_DISABLED",
	API_KEY_RATE_LIMITED: "API_KEY_RATE_LIMITED",
	API_KEY_UNAUTHORIZED: "API_KEY_UNAUTHORIZED",
	API_KEY_FORBIDDEN: "API_KEY_FORBIDDEN",
	API_KEY_BAD_REQUEST: "API_KEY_BAD_REQUEST",
} as const;
