export const errorCodes = {
	UNAUTHORIZED: "UNAUTHORIZED",
	INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
	INVALID_EMAIL: "INVALID_EMAIL",
	VERIFICATION_FAILED: "VERIFICATION_FAILED",
	VERIFICATION_TIMEOUT: "VERIFICATION_TIMEOUT",
	JOB_NOT_FOUND: "JOB_NOT_FOUND",
	JOB_UNAUTHORIZED: "JOB_UNAUTHORIZED",
	RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	BAD_REQUEST: "BAD_REQUEST",
} as const;
