export const errorCodes = {
    UNAUTHORIZED: "UNAUTHORIZED",
    NOT_MEMBER_OF_ORGANIZATION: "NOT_MEMBER_OF_ORGANIZATION",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    FILE_TOO_LARGE: "FILE_TOO_LARGE",
    INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
    UPLOAD_FAILED: "UPLOAD_FAILED",
    DELETE_FAILED: "DELETE_FAILED",
} as const;

